# workflow_pruner.yml
# This workflow prunes old workflow runs for an entire repository.
name: Workflow Run Pruner
on:
  schedule:
  - cron: '0 */12 * * *'  # GMT
  workflow_dispatch:
  push:

env:
  days: 7

jobs:
  prune:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Prune cancelled/skipped runs
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const cancelled = await github.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            per_page: 100,
            repo: context.repo.repo,
            status: 'cancelled',
          });

          const skipped = await github.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            per_page: 100,
            repo: context.repo.repo,
            status: 'skipped',
          });

          for (const response of [cancelled, skipped]) {
            for (const run of response.data.workflow_runs) {
              console.log(`Run id ${run.id} of '${run.name}' is a cancelled/skipped run. Deleting...`);
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
          }

    - name: Prune runs older than ${{ env.days }};
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const days_to_expiration = ${{ env.days }};
          const ms_in_day = 86400000;
          const now = Date.now();
          const pages = 5;

          // List of workflows to prune
          const workflows = [
            'build.yml'
          ]

          let runs_to_delete = [];

          for (const workflow of workflows) {
            for (let page = 0; page < pages; page += 1) {
              let response = await github.actions.listWorkflowRuns({
                owner: context.repo.owner,
                page: page,
                per_page: 100,
                repo: context.repo.repo,
                workflow_id: workflow
              });

              if (response.data.workflow_runs.length > 0) {
                for (const run of response.data.workflow_runs) {
                  if (now - Date.parse(run.created_at) > ms_in_day * days_to_expiration) {
                    runs_to_delete.push([run.id, run.name]);
                  }
                }
              }
            }
          }

          for (const run of runs_to_delete) {
            console.log(`Run id ${run[0]} of '${run[1]}' is older than ${days_to_expiration} days. Deleting...`);
            try {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run[0]
              });
            } catch (error) {
              // ignore errors
            }
          }

    - name: Remove runs of the cleanup workflow itself
      uses: actions/github-script@v4 # https://github.com/actions/github-script
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pages = 5;
          let runs_to_delete = [];

          for (let page = 0; page < pages; page += 1) {
            let response = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              page: page,
              per_page: 100,
              repo: context.repo.repo,
              workflow_id: 'workflow_pruner.yml'
            });

            if (response.data.workflow_runs.length > 0) {
              for (const run of response.data.workflow_runs) {
                runs_to_delete.push([run.id, run.name]);
              }
            }
          }

          for (const run of runs_to_delete) {
            console.log(`[Deleting] Run id ${run[0]} of '${run[1]}'.`);
            try {
              await github.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run[0]
              });
            } catch (error) {
              // ignore errors
            }
          }
